"""Canned Nominatim responses served by ``call_geocoding_api`` when ``settings.test_mode`` is set,
so tests never reach the live geocoding API. Keyed by query string; the value is the raw Nominatim
response list (an empty list means no results were found)."""

MOCK_GEOCODING_RESPONSES = {
    "90210, Beverly Hills, United States": [
        {
            "place_id": 320394032,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 3503615,
            "lat": "34.0696501",
            "lon": "-118.3963062",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 16,
            "importance": 0.6437262811065398,
            "addresstype": "town",
            "name": "Beverly Hills",
            "display_name": "Beverly Hills, Los Angeles County, California, United States",
            "address": {
                "town": "Beverly Hills",
                "county": "Los Angeles County",
                "state": "California",
                "ISO3166-2-lvl4": "US-CA",
                "country": "United States",
                "country_code": "us",
            },
            "boundingbox": ["34.0526685", "34.1124560", "-118.4270730", "-118.3715358"],
        }
    ],
    "10001, New York, United States": [
        {
            "place_id": 380806061,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "lat": "40.7485244",
            "lon": "-73.9940767",
            "class": "place",
            "type": "postcode",
            "place_rank": 21,
            "importance": 0.12000999999999995,
            "addresstype": "postcode",
            "name": "10001",
            "display_name": "10001, Manhattan, New York County, New York, United States",
            "address": {
                "postcode": "10001",
                "suburb": "Manhattan",
                "county": "New York County",
                "city": "New York",
                "state": "New York",
                "ISO3166-2-lvl4": "US-NY",
                "country": "United States",
                "country_code": "us",
            },
            "boundingbox": ["40.7034881", "40.7935605", "-74.0532957", "-73.9348592"],
        }
    ],
    "San Francisco, United States": [
        {
            "place_id": 323637204,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 111968,
            "lat": "37.7879363",
            "lon": "-122.4075201",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 12,
            "importance": 0.780971280931417,
            "addresstype": "city",
            "name": "San Francisco",
            "display_name": "San Francisco, California, United States",
            "address": {
                "city": "San Francisco",
                "state": "California",
                "ISO3166-2-lvl4": "US-CA",
                "country": "United States",
                "country_code": "us",
            },
            "boundingbox": ["37.6403143", "37.9296678", "-123.1738250", "-122.2814578"],
        }
    ],
    "SW1A 1AA, London, United Kingdom": [
        {
            "place_id": 379651284,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "lat": "51.5013375",
            "lon": "-0.1417955",
            "class": "place",
            "type": "postcode",
            "place_rank": 23,
            "importance": 0.09334333333333333,
            "addresstype": "postcode",
            "name": "SW1A 1AA",
            "display_name": "SW1A 1AA, City of Westminster, Greater London, England, United Kingdom",
            "address": {
                "postcode": "SW1A 1AA",
                "city": "City of Westminster",
                "ISO3166-2-lvl8": "GB-WSM",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["51.4950511", "51.5076238", "-0.1518679", "-0.1317232"],
        }
    ],
    "Germany": [
        {
            "place_id": 136725313,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 51477,
            "lat": "51.1638175",
            "lon": "10.4478313",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 4,
            "importance": 0.9528343247777981,
            "addresstype": "country",
            "name": "Germany",
            "display_name": "Germany",
            "address": {"country": "Germany", "country_code": "de"},
            "boundingbox": ["47.2701114", "55.0991610", "5.8663153", "15.0419309"],
        }
    ],
    "75001, Paris, France": [
        {
            "place_id": 88092976,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 10776952,
            "lat": "48.8625842",
            "lon": "2.3364289",
            "class": "boundary",
            "type": "postal_code",
            "place_rank": 21,
            "importance": 0.12000999999999995,
            "addresstype": "postcode",
            "name": "75001",
            "display_name": "75001, Paris, Ile-de-France, Metropolitan France, France",
            "address": {
                "postcode": "75001",
                "suburb": "Paris",
                "city_district": "Paris",
                "city": "Paris",
                "ISO3166-2-lvl6": "FR-75C",
                "state": "Ile-de-France",
                "ISO3166-2-lvl4": "FR-IDF",
                "region": "Metropolitan France",
                "country": "France",
                "country_code": "fr",
            },
            "boundingbox": ["48.8540428", "48.8699258", "2.3209018", "2.3509479"],
        }
    ],
    "Tokyo, Japan": [
        {
            "place_id": 261079222,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 1543125,
            "lat": "35.6768601",
            "lon": "139.7638947",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 8,
            "importance": 0.8337626616070368,
            "addresstype": "province",
            "name": "Tokyo",
            "display_name": "Tokyo, Japan",
            "address": {"province": "Tokyo", "ISO3166-2-lvl4": "JP-13", "country": "Japan", "country_code": "jp"},
            "boundingbox": ["20.2145811", "35.8984245", "135.8536855", "154.2055410"],
        }
    ],
    "M5V 3A8, Toronto, Canada": [
        {
            "place_id": 378183424,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "lat": "43.6477776",
            "lon": "-79.3951973",
            "class": "place",
            "type": "postcode",
            "place_rank": 21,
            "importance": 0.12000999999999995,
            "addresstype": "postcode",
            "name": "M5V 3A8",
            "display_name": "M5V 3A8, Toronto, Golden Horseshoe, Ontario, Canada",
            "address": {
                "postcode": "M5V 3A8",
                "city": "Toronto",
                "state_district": "Golden Horseshoe",
                "state": "Ontario",
                "ISO3166-2-lvl4": "CA-ON",
                "country": "Canada",
                "country_code": "ca",
            },
            "boundingbox": ["43.6027747", "43.6927800", "-79.4571730", "-79.3332244"],
        }
    ],
    "Amsterdam, Netherlands": [
        {
            "place_id": 154633226,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 271110,
            "lat": "52.3730796",
            "lon": "4.8924534",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 16,
            "importance": 0.7882100161799769,
            "addresstype": "city",
            "name": "Amsterdam",
            "display_name": "Amsterdam, North Holland, Netherlands",
            "address": {
                "city": "Amsterdam",
                "municipality": "Amsterdam",
                "state": "North Holland",
                "ISO3166-2-lvl4": "NL-NH",
                "country": "Netherlands",
                "country_code": "nl",
            },
            "boundingbox": ["52.2781742", "52.4310638", "4.7287776", "5.0791622"],
        }
    ],
    "Brazil": [
        {
            "place_id": 12593719,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 59470,
            "lat": "-10.3333333",
            "lon": "-53.2000000",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 4,
            "importance": 0.9029823800375192,
            "addresstype": "country",
            "name": "Brazil",
            "display_name": "Brazil",
            "address": {"country": "Brazil", "country_code": "br"},
            "boundingbox": ["-33.8694284", "5.2695808", "-73.9830625", "-28.6289646"],
        }
    ],
    "OX1 2JD, Oxford, United Kingdom": [
        {
            "place_id": 351429040,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "lat": "51.7583709",
            "lon": "-1.2618709",
            "class": "place",
            "type": "postcode",
            "place_rank": 25,
            "importance": 0.06667666666666666,
            "addresstype": "postcode",
            "name": "OX1 2JD",
            "display_name": "OX1 2JD, University Offices, Holywell, City Centre, Oxford, Oxfordshire, England, United Kingdom",
            "address": {
                "postcode": "OX1 2JD",
                "commercial": "University Offices",
                "quarter": "Holywell",
                "suburb": "City Centre",
                "city": "Oxford",
                "county": "Oxfordshire",
                "ISO3166-2-lvl6": "GB-OXF",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["51.7520799", "51.7646620", "-1.2720084", "-1.2517336"],
        }
    ],
    "Edinburgh, United Kingdom": [
        {
            "place_id": 254654291,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 1920901,
            "lat": "55.9533456",
            "lon": "-3.1883749",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 12,
            "importance": 0.7363481185006193,
            "addresstype": "city",
            "name": "City of Edinburgh",
            "display_name": "City of Edinburgh, Scotland, United Kingdom",
            "address": {
                "city": "City of Edinburgh",
                "ISO3166-2-lvl6": "GB-EDH",
                "state": "Scotland",
                "ISO3166-2-lvl4": "GB-SCT",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["55.8187919", "56.0040837", "-3.4495326", "-3.0749528"],
        }
    ],
    "United Kingdom": [
        {
            "place_id": 274782588,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 62149,
            "lat": "54.7023545",
            "lon": "-3.2765753",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 4,
            "importance": 0.9388533772580386,
            "addresstype": "country",
            "name": "United Kingdom",
            "display_name": "United Kingdom",
            "address": {"country": "United Kingdom", "country_code": "gb"},
            "boundingbox": ["49.6740000", "61.0610000", "-14.0155170", "2.0919117"],
        }
    ],
    "BS1 1AA, Bristol, United Kingdom": [],
    "M1 1AA, Manchester, United Kingdom": [
        {
            "place_id": 276701995,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "node",
            "osm_id": 11381278578,
            "lat": "53.4626401",
            "lon": "-2.2372955",
            "class": "office",
            "type": "company",
            "place_rank": 30,
            "importance": 7.817273212782509e-05,
            "addresstype": "office",
            "name": "Bright Biotech",
            "display_name": "Bright Biotech, 40, Pencroft Way, Manchester Science Park, Brunswick, Moss Side, Manchester, Greater Manchester, England, M15 6SZ, United Kingdom",
            "address": {
                "office": "Bright Biotech",
                "house_number": "40",
                "road": "Pencroft Way",
                "commercial": "Manchester Science Park",
                "quarter": "Brunswick",
                "suburb": "Moss Side",
                "city": "Manchester",
                "ISO3166-2-lvl8": "GB-MAN",
                "state_district": "Greater Manchester",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "postcode": "M15 6SZ",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["53.4625901", "53.4626901", "-2.2373455", "-2.2372455"],
        }
    ],
    "San Francisco": [
        {
            "place_id": 325364119,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 111968,
            "lat": "37.7879363",
            "lon": "-122.4075201",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 12,
            "importance": 0.780971280931417,
            "addresstype": "city",
            "name": "San Francisco",
            "display_name": "San Francisco, California, United States",
            "address": {
                "city": "San Francisco",
                "state": "California",
                "ISO3166-2-lvl4": "US-CA",
                "country": "United States",
                "country_code": "us",
            },
            "boundingbox": ["37.6403143", "37.9296678", "-123.1738250", "-122.2814578"],
        }
    ],
    "New York": [
        {
            "place_id": 359971500,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 175905,
            "lat": "40.7127281",
            "lon": "-74.0060152",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 10,
            "importance": 0.8817923363604117,
            "addresstype": "city",
            "name": "New York",
            "display_name": "New York, United States",
            "address": {
                "city": "New York",
                "state": "New York",
                "ISO3166-2-lvl4": "US-NY",
                "country": "United States",
                "country_code": "us",
            },
            "boundingbox": ["40.4765780", "40.9176300", "-74.2588430", "-73.7002330"],
        }
    ],
    "London, UK": [
        {
            "place_id": 416665509,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 175342,
            "lat": "51.5074456",
            "lon": "-0.1277653",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 10,
            "importance": 0.8920997258748663,
            "addresstype": "city",
            "name": "Greater London",
            "display_name": "Greater London, England, United Kingdom",
            "address": {
                "city": "Greater London",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["51.2867601", "51.6918741", "-0.5103751", "0.3340155"],
        }
    ],
    "UK": [
        {
            "place_id": 275211732,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 62149,
            "lat": "54.7023545",
            "lon": "-3.2765753",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 4,
            "importance": 0.9388533772580386,
            "addresstype": "country",
            "name": "United Kingdom",
            "display_name": "United Kingdom",
            "address": {"country": "United Kingdom", "country_code": "gb"},
            "boundingbox": ["49.6740000", "61.0610000", "-14.0155170", "2.0919117"],
        }
    ],
    "Edinburgh, UK": [
        {
            "place_id": 275600170,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 1920901,
            "lat": "55.9533456",
            "lon": "-3.1883749",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 12,
            "importance": 0.7363481185006193,
            "addresstype": "city",
            "name": "City of Edinburgh",
            "display_name": "City of Edinburgh, Scotland, United Kingdom",
            "address": {
                "city": "City of Edinburgh",
                "ISO3166-2-lvl6": "GB-EDH",
                "state": "Scotland",
                "ISO3166-2-lvl4": "GB-SCT",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["55.8187919", "56.0040837", "-3.4495326", "-3.0749528"],
        }
    ],
    "Manchester, UK": [
        {
            "place_id": 277422334,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "node",
            "osm_id": 294001443,
            "lat": "53.4794892",
            "lon": "-2.2451148",
            "class": "place",
            "type": "city",
            "place_rank": 16,
            "importance": 0.7396662642520947,
            "addresstype": "city",
            "name": "Manchester",
            "display_name": "Manchester, Lancashire, Greater Manchester, England, M60 2UH, United Kingdom",
            "address": {
                "city": "Manchester",
                "ISO3166-2-lvl8": "GB-MAN",
                "county": "Lancashire",
                "ISO3166-2-lvl6": "GB-LAN",
                "state_district": "Greater Manchester",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "postcode": "M60 2UH",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["53.3194892", "53.6394892", "-2.4051148", "-2.0851148"],
        }
    ],
    "London": [
        {
            "place_id": 436040256,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 175342,
            "lat": "51.5074456",
            "lon": "-0.1277653",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 10,
            "importance": 0.8920997258748663,
            "addresstype": "city",
            "name": "Greater London",
            "display_name": "Greater London, England, United Kingdom",
            "address": {
                "city": "Greater London",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["51.2867601", "51.6918741", "-0.5103751", "0.3340155"],
        }
    ],
    "Leeds, UK": [
        {
            "place_id": 277747412,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "node",
            "osm_id": 358309,
            "lat": "53.7974185",
            "lon": "-1.5437941",
            "class": "place",
            "type": "city",
            "place_rank": 16,
            "importance": 0.6780319497874053,
            "addresstype": "city",
            "name": "Leeds",
            "display_name": "Leeds, West Yorkshire, England, LS1 6AL, United Kingdom",
            "address": {
                "city": "Leeds",
                "ISO3166-2-lvl8": "GB-LDS",
                "state_district": "West Yorkshire",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "postcode": "LS1 6AL",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["53.6374185", "53.9574185", "-1.7037941", "-1.3837941"],
        }
    ],
    "Liverpool, UK": [
        {
            "place_id": 277402667,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 172987,
            "lat": "53.3933411",
            "lon": "-2.9166389",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 16,
            "importance": 0.7297576262804647,
            "addresstype": "city",
            "name": "Liverpool",
            "display_name": "Liverpool, Liverpool City Region, England, United Kingdom",
            "address": {
                "city": "Liverpool",
                "ISO3166-2-lvl8": "GB-LIV",
                "state_district": "Liverpool City Region",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["53.3115427", "53.4749885", "-3.0191726", "-2.8180003"],
        }
    ],
    "Cardiff, UK": [
        {
            "place_id": 282131296,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "node",
            "osm_id": 738885245,
            "lat": "51.4816546",
            "lon": "-3.1791934",
            "class": "place",
            "type": "city",
            "place_rank": 16,
            "importance": 0.6972041826939046,
            "addresstype": "city",
            "name": "Cardiff",
            "display_name": "Cardiff, Wales, CF10 2AF, United Kingdom",
            "address": {
                "city": "Cardiff",
                "county": "Cardiff",
                "ISO3166-2-lvl6": "GB-CRF",
                "state": "Wales",
                "ISO3166-2-lvl4": "GB-WLS",
                "postcode": "CF10 2AF",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["51.3216546", "51.6416546", "-3.3391934", "-3.0191934"],
        }
    ],
    "Newcastle, UK": [
        {
            "place_id": 253650069,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 142282,
            "lat": "54.9738474",
            "lon": "-1.6131572",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 16,
            "importance": 0.6753066932424819,
            "addresstype": "city",
            "name": "Newcastle upon Tyne",
            "display_name": "Newcastle upon Tyne, Tyne and Wear, North East, England, United Kingdom",
            "address": {
                "city": "Newcastle upon Tyne",
                "ISO3166-2-lvl8": "GB-NET",
                "county": "Tyne and Wear",
                "state_district": "North East",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["54.9590320", "55.0793823", "-1.7756721", "-1.5292003"],
        }
    ],
    "Birmingham, UK": [
        {
            "place_id": 258192808,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 162378,
            "lat": "52.4796992",
            "lon": "-1.9026911",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 16,
            "importance": 0.7330352634722094,
            "addresstype": "city",
            "name": "Birmingham",
            "display_name": "Birmingham, West Midlands, England, United Kingdom",
            "address": {
                "city": "Birmingham",
                "ISO3166-2-lvl8": "GB-BIR",
                "state_district": "West Midlands",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["52.3810530", "52.6087058", "-2.0336486", "-1.7288417"],
        }
    ],
    "Bristol, UK": [
        {
            "place_id": 280406549,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 5746665,
            "lat": "51.4538022",
            "lon": "-2.5972985",
            "class": "place",
            "type": "city",
            "place_rank": 16,
            "importance": 0.7042167330140456,
            "addresstype": "city",
            "name": "Bristol",
            "display_name": "Bristol, City of Bristol, West of England, England, United Kingdom",
            "address": {
                "city": "Bristol",
                "county": "City of Bristol",
                "ISO3166-2-lvl6": "GB-BST",
                "state_district": "West of England",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["51.3972838", "51.5444317", "-2.7183704", "-2.5104192"],
        }
    ],
    "Glasgow, UK": [
        {
            "place_id": 274690879,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "node",
            "osm_id": 11127374,
            "lat": "55.8611550",
            "lon": "-4.2501687",
            "class": "place",
            "type": "city",
            "place_rank": 16,
            "importance": 0.7520825832994846,
            "addresstype": "city",
            "name": "Glasgow",
            "display_name": "Glasgow, Glasgow City, Scotland, G2 1AL, United Kingdom",
            "address": {
                "city": "Glasgow",
                "county": "Glasgow City",
                "ISO3166-2-lvl6": "GB-GLG",
                "state": "Scotland",
                "ISO3166-2-lvl4": "GB-SCT",
                "postcode": "G2 1AL",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["55.7011550", "56.0211550", "-4.4101687", "-4.0901687"],
        }
    ],
    "Cambridge, UK": [
        {
            "place_id": 158329020,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 295355,
            "lat": "52.1975846",
            "lon": "0.1391537",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 16,
            "importance": 0.6990058432201166,
            "addresstype": "city",
            "name": "Cambridge",
            "display_name": "Cambridge, Cambridgeshire, Cambridgeshire and Peterborough, England, United Kingdom",
            "address": {
                "city": "Cambridge",
                "county": "Cambridgeshire",
                "ISO3166-2-lvl6": "GB-CAM",
                "state_district": "Cambridgeshire and Peterborough",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["52.1579417", "52.2372296", "0.0686389", "0.1845520"],
        }
    ],
    "Oxford, UK": [
        {
            "place_id": 281753943,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 394037,
            "lat": "51.7520131",
            "lon": "-1.2578499",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 16,
            "importance": 0.7168966844674067,
            "addresstype": "city",
            "name": "Oxford",
            "display_name": "Oxford, Oxfordshire, England, United Kingdom",
            "address": {
                "city": "Oxford",
                "county": "Oxfordshire",
                "ISO3166-2-lvl6": "GB-OXF",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["51.7109788", "51.7962658", "-1.3042472", "-1.1758134"],
        }
    ],
    "Reading, UK": [
        {
            "place_id": 281326525,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 115074,
            "lat": "51.4564242",
            "lon": "-0.9700664",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 12,
            "importance": 0.6182581361914773,
            "addresstype": "town",
            "name": "Reading",
            "display_name": "Reading, England, United Kingdom",
            "address": {
                "town": "Reading",
                "ISO3166-2-lvl6": "GB-RDG",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["51.4097528", "51.4931340", "-1.0529948", "-0.9284943"],
        }
    ],
    "Brighton, UK": [
        {
            "place_id": 280068258,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "node",
            "osm_id": 1326762432,
            "lat": "50.8214626",
            "lon": "-0.1400561",
            "class": "place",
            "type": "city",
            "place_rank": 16,
            "importance": 0.6542525418875271,
            "addresstype": "city",
            "name": "Brighton",
            "display_name": "Brighton, Brighton and Hove, England, BN1 1HJ, United Kingdom",
            "address": {
                "city": "Brighton",
                "county": "Brighton and Hove",
                "ISO3166-2-lvl6": "GB-BNH",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "postcode": "BN1 1HJ",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["50.6614626", "50.9814626", "-0.3000561", "0.0199439"],
        }
    ],
    "Southampton, UK": [
        {
            "place_id": 282524141,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 127864,
            "lat": "50.9025349",
            "lon": "-1.4041890",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 12,
            "importance": 0.6611172127446537,
            "addresstype": "city",
            "name": "Southampton",
            "display_name": "Southampton, England, United Kingdom",
            "address": {
                "city": "Southampton",
                "ISO3166-2-lvl6": "GB-STH",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["50.8715095", "50.9561307", "-1.4790050", "-1.3219862"],
        }
    ],
    "Nottingham, UK": [
        {
            "place_id": 281072252,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 123292,
            "lat": "52.9534193",
            "lon": "-1.1496461",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 12,
            "importance": 0.6753241103588093,
            "addresstype": "city",
            "name": "Nottingham",
            "display_name": "Nottingham, Nottinghamshire, East Midlands, England, United Kingdom",
            "address": {
                "city": "Nottingham",
                "ISO3166-2-lvl6": "GB-NTT",
                "county": "Nottinghamshire",
                "state_district": "East Midlands",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["52.8890083", "53.0186721", "-1.2469560", "-1.0861189"],
        }
    ],
    "Sheffield, UK": [
        {
            "place_id": 277849449,
            "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright",
            "osm_type": "relation",
            "osm_id": 106956,
            "lat": "53.3806626",
            "lon": "-1.4702278",
            "class": "boundary",
            "type": "administrative",
            "place_rank": 16,
            "importance": 0.6799988915424466,
            "addresstype": "city",
            "name": "Sheffield",
            "display_name": "Sheffield, South Yorkshire, England, United Kingdom",
            "address": {
                "city": "Sheffield",
                "ISO3166-2-lvl8": "GB-SHF",
                "state_district": "South Yorkshire",
                "state": "England",
                "ISO3166-2-lvl4": "GB-ENG",
                "country": "United Kingdom",
                "country_code": "gb",
            },
            "boundingbox": ["53.3045116", "53.5031042", "-1.8014715", "-1.3246685"],
        }
    ],
}
