-- Schema of the public database immediately before the Alembic chain begins.
--
-- Generated from the SQLAlchemy models at commit 86ea019d~1 (2025-10-12), the parent of
-- "Implement email verification feature", which introduced the columns the root revision
-- 8a882611d98c adds. Sources at that commit were backend/app/models.py and
-- backend/app/eis/models.py; Base lived in app/database.py and the only settings value the
-- models read was min_password_length (8), inlined below in the user check constraint.
--
-- The migration chain cannot build a database from scratch: 8a882611d98c starts with
-- op.add_column("user", ...) because it was autogenerated against a schema create_all had
-- already produced. This file is that schema, so the chain can be replayed from it in
-- tests/test_migrations.py.
--
-- This is a record of history: do not regenerate or edit it to match the current models.
-- alembic_version is deliberately absent, alembic creates it on the first upgrade.

CREATE TABLE eis_service_log (
	run_duration FLOAT, 
	run_datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	is_success BOOLEAN, 
	error_message VARCHAR NOT NULL, 
	job_success_n INTEGER NOT NULL, 
	job_fail_n INTEGER NOT NULL, 
	users_processed_n INTEGER NOT NULL, 
	emails_found_n INTEGER NOT NULL, 
	emails_saved_n INTEGER NOT NULL, 
	jobs_extracted_n INTEGER NOT NULL, 
	linkedin_job_n INTEGER NOT NULL, 
	indeed_job_n INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE setting (
	name VARCHAR NOT NULL, 
	value VARCHAR NOT NULL, 
	description VARCHAR, 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (name)
);

CREATE TABLE "user" (
	password VARCHAR NOT NULL, 
	email VARCHAR NOT NULL, 
	theme VARCHAR DEFAULT 'mixed-berry' NOT NULL, 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	is_admin BOOLEAN DEFAULT false NOT NULL, 
	last_login TIMESTAMP WITH TIME ZONE, 
	chase_threshold INTEGER DEFAULT '30' NOT NULL, 
	deadline_threshold INTEGER DEFAULT '30' NOT NULL, 
	update_limit INTEGER DEFAULT '10' NOT NULL, 
	toast_active BOOLEAN DEFAULT false NOT NULL, 
	default_currency VARCHAR DEFAULT 'GBP' NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT minimum_password_length CHECK (length(password) >= 8), 
	UNIQUE (email)
);

CREATE TABLE aggregator (
	name VARCHAR NOT NULL, 
	url VARCHAR NOT NULL, 
	owner_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_owner_aggregator_name UNIQUE (owner_id, name), 
	FOREIGN KEY(owner_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE company (
	name VARCHAR NOT NULL, 
	description VARCHAR, 
	url VARCHAR, 
	owner_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_owner_company_name UNIQUE (owner_id, name), 
	FOREIGN KEY(owner_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE file (
	filename VARCHAR NOT NULL, 
	content VARCHAR NOT NULL, 
	type VARCHAR NOT NULL, 
	size INTEGER NOT NULL, 
	owner_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(owner_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE job_alert_email (
	external_email_id VARCHAR NOT NULL, 
	subject VARCHAR, 
	sender VARCHAR, 
	date_received TIMESTAMP WITH TIME ZONE, 
	platform VARCHAR, 
	body VARCHAR, 
	service_log_id INTEGER, 
	owner_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT unique_email_per_owner UNIQUE (external_email_id, owner_id), 
	UNIQUE (external_email_id), 
	FOREIGN KEY(service_log_id) REFERENCES eis_service_log (id) ON DELETE SET NULL, 
	FOREIGN KEY(owner_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE keyword (
	name VARCHAR NOT NULL, 
	owner_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_owner_keyword_name UNIQUE (owner_id, name), 
	FOREIGN KEY(owner_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE location (
	postcode VARCHAR, 
	city VARCHAR, 
	country VARCHAR, 
	owner_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT location_data_required CHECK (postcode IS NOT NULL OR city IS NOT NULL OR country IS NOT NULL), 
	FOREIGN KEY(owner_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE scraped_job (
	external_job_id VARCHAR NOT NULL, 
	is_scraped BOOLEAN DEFAULT false NOT NULL, 
	is_failed BOOLEAN DEFAULT false NOT NULL, 
	scrape_error VARCHAR, 
	scrape_datetime TIMESTAMP WITH TIME ZONE, 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	is_imported BOOLEAN DEFAULT false NOT NULL, 
	title VARCHAR, 
	description VARCHAR, 
	salary_min FLOAT, 
	salary_max FLOAT, 
	url VARCHAR, 
	deadline TIMESTAMP WITH TIME ZONE, 
	company VARCHAR, 
	location VARCHAR, 
	owner_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT unique_job_per_owner UNIQUE (external_job_id, owner_id), 
	FOREIGN KEY(owner_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE job (
	title VARCHAR NOT NULL, 
	description VARCHAR, 
	salary_min FLOAT, 
	salary_max FLOAT, 
	salary_currency VARCHAR, 
	url VARCHAR, 
	personal_rating INTEGER, 
	note VARCHAR, 
	deadline TIMESTAMP WITH TIME ZONE, 
	followup_snooze_datetime TIMESTAMP WITH TIME ZONE, 
	attendance_type VARCHAR, 
	application_date TIMESTAMP WITH TIME ZONE, 
	application_url VARCHAR, 
	application_status VARCHAR, 
	applied_via VARCHAR, 
	application_note VARCHAR, 
	company_id INTEGER, 
	location_id INTEGER, 
	duplicate_id INTEGER, 
	source_id INTEGER, 
	application_aggregator_id INTEGER, 
	cv_id INTEGER, 
	cover_letter_id INTEGER, 
	owner_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT valid_rating_range CHECK (personal_rating >= 1 AND personal_rating <= 5), 
	CONSTRAINT valid_salary_range CHECK (salary_min <= salary_max), 
	CONSTRAINT valid_attendance_type_values CHECK (attendance_type IN ('on-site', 'remote', 'hybrid')), 
	CONSTRAINT valid_application_status_values CHECK (application_status IN ('applied', 'interview', 'offer', 'rejected', 'withdrawn')), 
	CONSTRAINT valid_applied_via_values CHECK (applied_via IN ('aggregator', 'email', 'phone', 'other')), 
	FOREIGN KEY(company_id) REFERENCES company (id) ON DELETE SET NULL, 
	FOREIGN KEY(location_id) REFERENCES location (id) ON DELETE SET NULL, 
	FOREIGN KEY(duplicate_id) REFERENCES job (id) ON DELETE SET NULL, 
	FOREIGN KEY(source_id) REFERENCES aggregator (id) ON DELETE SET NULL, 
	FOREIGN KEY(application_aggregator_id) REFERENCES aggregator (id) ON DELETE SET NULL, 
	FOREIGN KEY(cv_id) REFERENCES file (id) ON DELETE SET NULL, 
	FOREIGN KEY(cover_letter_id) REFERENCES file (id) ON DELETE SET NULL, 
	FOREIGN KEY(owner_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE INDEX ix_job_application_aggregator_id ON job (application_aggregator_id);

CREATE INDEX ix_job_company_id ON job (company_id);

CREATE INDEX ix_job_cover_letter_id ON job (cover_letter_id);

CREATE INDEX ix_job_cv_id ON job (cv_id);

CREATE INDEX ix_job_duplicate_id ON job (duplicate_id);

CREATE INDEX ix_job_location_id ON job (location_id);

CREATE INDEX ix_job_source_id ON job (source_id);

CREATE TABLE jobalertemail_scrapedjob_mapping (
	email_id INTEGER NOT NULL, 
	job_id INTEGER NOT NULL, 
	PRIMARY KEY (email_id, job_id), 
	FOREIGN KEY(email_id) REFERENCES job_alert_email (id) ON DELETE CASCADE, 
	FOREIGN KEY(job_id) REFERENCES scraped_job (id) ON DELETE CASCADE
);

CREATE TABLE person (
	first_name VARCHAR NOT NULL, 
	last_name VARCHAR NOT NULL, 
	email VARCHAR, 
	phone VARCHAR, 
	role VARCHAR, 
	linkedin_url VARCHAR, 
	company_id INTEGER, 
	owner_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(company_id) REFERENCES company (id) ON DELETE SET NULL, 
	FOREIGN KEY(owner_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE INDEX ix_person_company_id ON person (company_id);

CREATE TABLE interview (
	date TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	type VARCHAR NOT NULL, 
	note VARCHAR, 
	attendance_type VARCHAR, 
	location_id INTEGER, 
	job_id INTEGER NOT NULL, 
	owner_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT valid_attendance_type_values CHECK (attendance_type IN ('on-site', 'remote')), 
	FOREIGN KEY(location_id) REFERENCES location (id) ON DELETE SET NULL, 
	FOREIGN KEY(job_id) REFERENCES job (id) ON DELETE CASCADE, 
	FOREIGN KEY(owner_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE INDEX ix_interview_job_id ON interview (job_id);

CREATE INDEX ix_interview_location_id ON interview (location_id);

CREATE TABLE job_application_update (
	date TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	note VARCHAR, 
	type VARCHAR NOT NULL, 
	job_id INTEGER NOT NULL, 
	owner_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	modified_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT valid_update_type_values CHECK (type IN ('received', 'sent')), 
	FOREIGN KEY(job_id) REFERENCES job (id) ON DELETE CASCADE, 
	FOREIGN KEY(owner_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE job_contact_mapping (
	job_id INTEGER NOT NULL, 
	person_id INTEGER NOT NULL, 
	PRIMARY KEY (job_id, person_id), 
	FOREIGN KEY(job_id) REFERENCES job (id) ON DELETE CASCADE, 
	FOREIGN KEY(person_id) REFERENCES person (id) ON DELETE CASCADE
);

CREATE TABLE job_keyword_mapping (
	job_id INTEGER NOT NULL, 
	keyword_id INTEGER NOT NULL, 
	PRIMARY KEY (job_id, keyword_id), 
	FOREIGN KEY(job_id) REFERENCES job (id) ON DELETE CASCADE, 
	FOREIGN KEY(keyword_id) REFERENCES keyword (id) ON DELETE CASCADE
);

CREATE TABLE interview_interviewer_mapping (
	interview_id INTEGER NOT NULL, 
	person_id INTEGER NOT NULL, 
	PRIMARY KEY (interview_id, person_id), 
	FOREIGN KEY(interview_id) REFERENCES interview (id) ON DELETE CASCADE, 
	FOREIGN KEY(person_id) REFERENCES person (id) ON DELETE CASCADE
);
