"""improved job rating table

Revision ID: 2eea13943433
Revises: e72405e70d74
Create Date: 2025-12-17 08:31:10.837644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2eea13943433'
down_revision: Union[str, None] = 'e72405e70d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_rating_service_log', sa.Column('user_found_ids', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.add_column('job_rating_service_log', sa.Column('user_processed_ids', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.drop_column('job_rating_service_log', 'rated_job_skipped_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_rating_service_log', sa.Column('rated_job_skipped_ids', postgresql.ARRAY(sa.INTEGER()), server_default=sa.text("'{}'::integer[]"), autoincrement=False, nullable=False))
    op.drop_column('job_rating_service_log', 'user_processed_ids')
    op.drop_column('job_rating_service_log', 'user_found_ids')
    # ### end Alembic commands ###
