"""improved job scraping service log

Revision ID: 5a49153b049a
Revises: 2eea13943433
Create Date: 2025-12-19 14:39:48.117849

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a49153b049a"
down_revision: Union[str, None] = "2eea13943433"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_email_scraping_platform_stat",
        sa.Column("job_to_scrape_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_email_scraping_platform_stat", "job_to_scrape_ids")
    # ### end Alembic commands ###
