"""followup + spontaneous + scraping filters

Revision ID: 60f87f14d1ef
Revises: 5a49153b049a
Create Date: 2025-12-31 18:14:41.640435

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "60f87f14d1ef"
down_revision: Union[str, None] = "5a49153b049a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scraping_filter",
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("operator", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("case_sensitive", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "operator IN ('contains', 'equals', 'starts_with', 'ends_with', 'less_than', 'greater_than', 'not_contains', 'not_equals')",
            name="valid_filter_operator",
        ),
        sa.CheckConstraint(
            "type IN ('title', 'company', 'location', 'location_city', 'location_country', 'salary_min', 'salary_max', 'attendance_type')",
            name="valid_filter_type",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "speculative_application",
        sa.Column("date", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("contact_email", sa.String(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "speculative_application_contact_mapping",
        sa.Column("speculative_application_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["speculative_application_id"], ["speculative_application.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("speculative_application_id", "person_id"),
    )
    op.add_column(
        "job_email_scraping_platform_stat",
        sa.Column("job_scrape_filtered_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
    )
    op.add_column("person", sa.Column("is_recruiter", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("scraped_job", sa.Column("filter_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "scraped_job", "scraping_filter", ["filter_id"], ["id"], ondelete="SET NULL")
    op.add_column("user", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("last_name", sa.String(), nullable=True))

    op.drop_constraint("valid_applied_via_values", "job", type_="check")
    op.create_check_constraint(
        "valid_applied_via_values",
        "job",
        "applied_via IN ('aggregator', 'email', 'company_website', 'phone', 'other')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    op.drop_constraint(None, "scraped_job", type_="foreignkey")
    op.drop_column("scraped_job", "filter_id")
    op.drop_column("person", "is_recruiter")
    op.drop_column("job_email_scraping_platform_stat", "job_scrape_filtered_ids")
    op.drop_table("speculative_application_contact_mapping")
    op.drop_table("speculative_application")
    op.drop_table("scraping_filter")
    op.drop_constraint("valid_applied_via_values", "your_table_name", type_="check")
    op.create_check_constraint(
        "valid_applied_via_values", "your_table_name", "applied_via IN ('aggregator', 'email', 'phone', 'other')"
    )


# ### end Alembic commands ###
