"""empty message

Revision ID: 77b1a20511b7
Revises: a12b8efb3046
Create Date: 2026-02-27 17:45:37.248484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "77b1a20511b7"
down_revision: Union[str, None] = "a12b8efb3046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_preferences",
        sa.Column("extension_banner_dismissed", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_preferences", "extension_banner_dismissed")
    # ### end Alembic commands ###
