"""add table columns and sort to
  user preferences

Revision ID: 84de93787471
Revises: a9b8c7d6e5f4
Create Date: 2026-05-21 23:28:23.147674

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84de93787471"
down_revision: Union[str, None] = "a9b8c7d6e5f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("is_favourite", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("job", sa.Column("scraped_job_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_job_scraped_job_id"), "job", ["scraped_job_id"], unique=False)
    op.create_foreign_key(None, "job", "scraped_job", ["scraped_job_id"], ["id"], ondelete="SET NULL")
    op.drop_constraint(op.f("unique_email_per_owner"), "job_email", type_="unique")
    op.create_unique_constraint("unique_email_per_owner", "job_email", ["external_email_id", "is_tour", "owner_id"])
    op.add_column(
        "job_email_scraping_service_log",
        sa.Column("is_tour", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("user_preferences", sa.Column("table_columns", sa.JSON(), nullable=True))
    op.add_column("user_preferences", sa.Column("table_sort", sa.JSON(), nullable=True))
    op.alter_column(
        "user_preferences", "dashboard_layout", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_preferences", "dashboard_layout", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True
    )
    op.drop_column("user_preferences", "table_sort")
    op.drop_column("user_preferences", "table_columns")
    op.drop_column("job_email_scraping_service_log", "is_tour")
    op.drop_constraint("unique_email_per_owner", "job_email", type_="unique")
    op.create_unique_constraint(
        op.f("unique_email_per_owner"),
        "job_email",
        ["external_email_id", "owner_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(op.f("job_scraped_job_id_fkey"), "job", type_="foreignkey")
    op.drop_index(op.f("ix_job_scraped_job_id"), table_name="job")
    op.drop_column("job", "scraped_job_id")
    op.drop_column("job", "is_favourite")
    # ### end Alembic commands ###
