"""Added email verification and password reset

Revision ID: 8a882611d98c
Revises:
Create Date: 2025-10-19 18:43:43.928139

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a882611d98c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("user", sa.Column("verification_token", sa.String(), nullable=True))
    op.add_column("user", sa.Column("verification_token_created_at", sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column("user", sa.Column("password_reset_token", sa.String(), nullable=True))
    op.add_column("user", sa.Column("password_reset_token_created_at", sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_unique_constraint(None, "user", ["password_reset_token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("user_password_reset_token_key"), "user", type_="unique")
    op.drop_column("user", "password_reset_token_created_at")
    op.drop_column("user", "password_reset_token")
    op.drop_column("user", "verification_token_created_at")
    op.drop_column("user", "verification_token")
    op.drop_column("user", "is_verified")
    # ### end Alembic commands ###
