"""Added new columns for email change verification

Revision ID: 99db4c2aaf82
Revises:
Create Date: 2025-11-10 20:50:15.996276

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "99db4c2aaf82"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("pending_email", sa.String(), nullable=True))
    op.add_column("user", sa.Column("email_change_token", sa.String(), nullable=True))
    op.add_column("user", sa.Column("email_change_token_created_at", sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column("user", sa.Column("token_version", sa.Integer(), nullable=False, server_default="0"))
    op.alter_column("user", "chase_threshold", server_default="14")
    op.alter_column("user", "deadline_threshold", server_default="7")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "token_version")
    op.drop_column("user", "email_change_token_created_at")
    op.drop_column("user", "email_change_token")
    op.drop_column("user", "pending_email")
    op.alter_column("user", "chase_threshold", server_default="30")
    op.alter_column("user", "deadline_threshold", server_default="30")
    # ### end Alembic commands ###
