"""toast + ai rating

Revision ID: e72405e70d74
Revises: efcdbc1cf88a
Create Date: 2025-12-15 23:22:52.359967

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e72405e70d74"
down_revision: Union[str, None] = "99db4c2aaf82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jobalertemail_scrapedjob_mapping")
    op.drop_table("job_alert_email")
    op.drop_table("eis_service_log")

    op.create_table(
        "job_email_scraping_service_log",
        sa.Column("user_found_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("user_processed_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("email_found_n", sa.Integer(), nullable=False),
        sa.Column("run_duration", sa.Float(), nullable=True),
        sa.Column("run_datetime", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_rating_service_log",
        sa.Column("rated_job_found_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("rated_job_succeeded_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("rated_job_failed_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("rated_job_skipped_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("run_duration", sa.Float(), nullable=True),
        sa.Column("run_datetime", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_email",
        sa.Column("external_email_id", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("sender", sa.String(), nullable=False),
        sa.Column("date_received", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("job_found_n", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("alert_name", sa.String(), nullable=True),
        sa.Column("service_log_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_log_id"], ["job_email_scraping_service_log.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_email_id"),
        sa.UniqueConstraint("external_email_id", "owner_id", name="unique_email_per_owner"),
    )
    op.create_table(
        "job_email_scraping_platform_stat",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email_saved_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("email_skipped_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("job_found_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("job_scrape_failed_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("job_scrape_succeeded_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("job_scrape_copied_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("job_scrape_skipped_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False),
        sa.Column("service_log_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["service_log_id"], ["job_email_scraping_service_log.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("service_log_id", "name", name="unique_platform_per_service_log"),
    )
    op.create_table(
        "job_email_scraping_service_error",
        sa.Column("error_type", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("traceback", sa.String(), nullable=False),
        sa.Column("service_log_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["service_log_id"], ["job_email_scraping_service_log.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_qualification",
        sa.Column("experience", sa.String(), nullable=True),
        sa.Column("skills", sa.String(), nullable=True),
        sa.Column("qualities", sa.String(), nullable=True),
        sa.Column("education", sa.String(), nullable=True),
        sa.Column("interests", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_rating",
        sa.Column("overall_score", sa.Integer(), nullable=True),
        sa.Column("technical_score", sa.Integer(), nullable=True),
        sa.Column("experience_score", sa.Integer(), nullable=True),
        sa.Column("educational_score", sa.Integer(), nullable=True),
        sa.Column("interest_score", sa.Integer(), nullable=True),
        sa.Column("feedback", sa.String(), nullable=True),
        sa.Column("script_version", sa.Integer(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("scraped_job_id", sa.Integer(), nullable=False),
        sa.Column("user_qualification_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scraped_job_id"], ["scraped_job.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_qualification_id"], ["user_qualification.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobemail_scrapedjob_mapping",
        sa.Column("email_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["email_id"], ["job_email.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["scraped_job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("email_id", "job_id"),
    )

    op.add_column("scraped_job", sa.Column("platform", sa.String(), nullable=False))
    op.add_column("scraped_job", sa.Column("salary_currency", sa.String(), nullable=True))
    op.add_column("scraped_job", sa.Column("raw_url", sa.String(), nullable=True))
    op.add_column("scraped_job", sa.Column("location_postcode", sa.String(), nullable=True))
    op.add_column("scraped_job", sa.Column("location_city", sa.String(), nullable=True))
    op.add_column("scraped_job", sa.Column("location_country", sa.String(), nullable=True))
    op.add_column("scraped_job", sa.Column("attendance_type", sa.String(), nullable=True))
    op.add_column("scraped_job", sa.Column("service_log_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "scraped_job", "job_email_scraping_service_log", ["service_log_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("user", sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_demo")
    op.drop_constraint(op.f("scraped_job_service_log_id_fkey"), "scraped_job", type_="foreignkey")
    op.drop_column("scraped_job", "service_log_id")
    op.drop_column("scraped_job", "attendance_type")
    op.drop_column("scraped_job", "location_country")
    op.drop_column("scraped_job", "location_city")
    op.drop_column("scraped_job", "location_postcode")
    op.drop_column("scraped_job", "raw_url")
    op.drop_column("scraped_job", "salary_currency")
    op.drop_column("scraped_job", "platform")
    op.drop_table("jobemail_scrapedjob_mapping")
    op.drop_table("job_rating")
    op.drop_table("user_qualification")
    op.drop_table("job_email_scraping_service_error")
    op.drop_table("job_email_scraping_platform_stat")
    op.drop_table("job_email")
    op.drop_table("job_rating_service_log")
    op.drop_table("job_email_scraping_service_log")
    op.create_table(
        "eis_service_log",
        sa.Column("run_duration", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("run_datetime", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("job_success_n", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("job_fail_n", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("users_processed_n", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("emails_found_n", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("emails_saved_n", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("jobs_extracted_n", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("linkedin_job_n", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("indeed_job_n", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('eis_service_log_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="eis_service_log_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "job_alert_email",
        sa.Column("external_email_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("subject", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("sender", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("date_received", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("platform", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("body", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("service_log_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name=op.f("job_alert_email_owner_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["service_log_id"],
            ["eis_service_log.id"],
            name=op.f("job_alert_email_service_log_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("job_alert_email_pkey")),
        sa.UniqueConstraint(
            "external_email_id",
            "owner_id",
            name=op.f("unique_email_per_owner"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "external_email_id",
            name=op.f("job_alert_email_external_email_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "jobalertemail_scrapedjob_mapping",
        sa.Column("email_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("job_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["job_alert_email.id"],
            name=op.f("jobalertemail_scrapedjob_mapping_email_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["scraped_job.id"],
            name=op.f("jobalertemail_scrapedjob_mapping_job_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("email_id", "job_id", name=op.f("jobalertemail_scrapedjob_mapping_pkey")),
    )
    # ### end Alembic commands ###
