import pytest


class ScraperTestBase:

    title = None
    company = None
    platform = None
    location = None
    attendance_type = None
    salary_min = None
    salary_max = None
    salary_currency = None
    description = None
    file = None

    def get_scraper(self):
        if self.platform == "linkedin":
            return "scrapeLinkedInJob"
        elif self.platform == "indeed":
            return "scrapeIndeedJob"
        elif self.platform == "veganjobs":
            return "scrapeVeganJobsJob"
        elif self.platform == "nhs":
            return "scrapeNhsJob"
        raise AssertionError(f"Unknown platform: {self.platform}")

    @pytest.fixture(scope="class")
    def data(self, scrape) -> dict:
        driver = scrape(self.file)
        return driver.execute_script(f"return {self.get_scraper()}();")

    def test_title(self, data) -> None:
        assert data["title"] == self.title

    def test_company(self, data) -> None:
        assert data["company"] == self.company

    def test_location(self, data) -> None:
        assert data["location"] == self.location

    def test_attendance_type(self, data) -> None:
        assert data["attendance_type"] == self.attendance_type

    def test_salary(self, data) -> None:
        assert data.get("salary_min") == self.salary_min
        assert data.get("salary_max") == self.salary_max
        assert data.get("salary_currency") == self.salary_currency

    def test_description_has_bullets(self, data) -> None:
        assert data["description"] == self.description


class TestLinkedinJobMain(ScraperTestBase):

    title = "Controls Engineer (Highly Technical Manufacturing) - to £65k - ID45697"
    company = "Humand Talent"
    platform = "linkedin"
    location = "Witney, England, United Kingdom"
    attendance_type = "hybrid"
    salary_min = 50_000
    salary_max = 65_000
    salary_currency = "GBP"
    description = (
        "Do you love designing elegant control systems for complex, real-world "
        "challenges?\n"
        "\n"
        "Are you looking to apply your expertise to next-generation, high-precision "
        "technology?\n"
        "\n"
        "Ready to take the technical lead on innovations used by major global "
        "manufacturers?\n"
        "\n"
        "Our client, a growing high-tech engineering company based in the Oxfordshire "
        "area, is seeking a Senior Controls Engineer to drive development across a "
        "suite of highly technical products. This is a chance to lead technically "
        "challenging projects at the cutting edge of automation, measurement, and "
        "systems integration, all in a collaborative and fast-paced R&D environment.\n"
        "\n"
        "You'll join a multidisciplinary team working on solutions that push the "
        "boundaries of speed and precision, supporting technologies used in advanced "
        "manufacturing and research worldwide.\n"
        "\n"
        "Why This Role is Great:\n"
        "\n"
        "- Lead the design, development, and optimisation of precision control "
        "systems used in highly specialised equipment.\n"
        "- Take ownership of system performance - from concept through to validation "
        "and troubleshooting.\n"
        "- Work at the sub-nanometre scale, helping to solve complex control and "
        "noise challenges.\n"
        "- Act as the technical authority for controls across multiple modules and "
        "system stages.\n"
        "- Collaborate with electronics, software, and mechanical teams in a "
        "hands-on, innovation-focused environment.\n"
        "- Influence future system architecture through continuous learning, "
        "analysis, and design evolution.\n"
        "- Contribute to the company's reputation for technical excellence and "
        "cutting-edge product development.\n"
        "\n"
        "About You:\n"
        "You might come from a background in engineering, physics, mechatronics or "
        "applied systems, with a proven track record in developing complex control "
        "systems. Whether your experience comes from high-end manufacturing, "
        "automation, scientific instrumentation, or another precision field, we're "
        "open to transferable skills.\n"
        "\n"
        "You'll be comfortable leading technical discussions, validating performance "
        "through testing, and translating complex theory into practical design.\n"
        "\n"
        "Skills & Experience That Would Be a Great Match:\n"
        "\n"
        "We're especially keen to hear from people with:\n"
        "\n"
        "- Strong understanding of control theory, feedback and feedforward loops\n"
        "- Experience acting as a technical lead on controls or automation systems\n"
        "- A hands-on approach to experimental setup, testing, and troubleshooting\n"
        "- Solid communication skills, able to work with diverse stakeholders\n"
        "- Proven experience (5+ years) in relevant engineering roles\n"
        "\n"
        "Desirable experience includes:\n"
        "\n"
        "- Knowledge of digital filtering, ideally in FPGAs\n"
        "- Familiarity with piezo systems and control challenges like hysteresis\n"
        "- Exposure to metrology, motion systems, or instrumentation\n"
        "- Experience guiding systems through EMC or regulatory testing\n"
        "- Understanding of PLC programming or automation controls\n"
        "\n"
        "What's in It for You:\n"
        "\n"
        "- £60,000-£65,000 salary\n"
        "- Annual bonus\n"
        "- EMI Share Scheme\n"
        "- Flexible working hours\n"
        "- 25 days' holiday + bank holidays\n"
        "- Pension scheme\n"
        "- An exciting, supportive environment where your technical leadership is "
        "truly valued\n"
        "\n"
        "Inclusion & Diversity Statement:\n"
        "We and our client are committed to creating an inclusive, respectful, and "
        "diverse working environment. We strongly encourage applications from "
        "candidates of all backgrounds and identities. If you don't meet every "
        "requirement but believe you have skills or experience that align with the "
        "role, we'd still love to hear from you.\n"
        "\n"
        "Excited by the opportunity to shape high-precision systems of the future?\n"
        "\n"
        "Apply now to learn more about this unique Senior Controls Engineer "
        "opportunity."
    )
    file = "Linkedin_main.html"


class TestLinkedinJobView(ScraperTestBase):
    """LinkedIn job page using the new randomised-class layout (data-view-name / data-testid based)."""

    title = "AI Automation Engineer Remote"
    company = "Apply4U"
    platform = "linkedin"
    location = "United Kingdom"
    attendance_type = "remote"
    salary_min = 55_000
    salary_max = 80_000
    salary_currency = "GBP"
    description = (
        "AI Automation Engineer (Remote - UK)\n"
        "Location: Fully Remote - United Kingdom\n"
        "Salary: £55,000 - £80,000 per annum (DOE)\n"
        "Job Type: Full-time, Permanent\n"
        "About the Opportunity\n"
        "One of our clients is looking for a highly skilled AI Automation Engineer "
        "to design, build, and deploy intelligent automation solutions across their "
        "business operations. This fully remote UK-based role is ideal for someone "
        "with strong experience in AI tools, workflow automation, APIs, and system "
        "integrations.\n"
        "You'll work at the intersection of AI, process improvement, and "
        "engineering - identifying opportunities to streamline workflows and "
        "implementing scalable automation solutions that drive efficiency and "
        "innovation.\n"
        "Key Responsibilities\n"
        "\n"
        "- Design and implement AI-driven automation workflows across business "
        "functions\n"
        "- Build and integrate systems using APIs and automation platforms\n"
        "- Develop and deploy LLM-based solutions (e.g., chatbots, internal tools, "
        "document automation)\n"
        "- Optimise processes using AI, RPA, and scripting solutions\n"
        "- Collaborate with product, operations, and engineering teams to identify "
        "automation opportunities\n"
        "- Ensure automation solutions are secure, scalable, and maintainable\n"
        "- Monitor performance and continuously improve automation pipelines\n"
        "- Document processes and technical configurations\n"
        "\n"
        "Required Skills & Experience\n"
        "\n"
        "- Proven experience in automation engineering, AI development, or workflow "
        "automation\n"
        "- Strong programming skills (Python preferred; JavaScript beneficial)\n"
        "- Experience integrating APIs and working with RESTful services\n"
        "- Familiarity with AI/LLM platforms and prompt engineering\n"
        "- Experience with automation tools (Zapier, Make, Power Automate, UiPath, "
        "etc.)\n"
        "- Knowledge of cloud environments (AWS, Azure, or GCP)\n"
        "- Strong analytical and problem-solving mindset\n"
        "- Ability to work independently in a remote-first environment\n"
        "\n"
        "Desirable (Not Essential)\n"
        "\n"
        "- Experience building AI-powered internal tools or SaaS integrations\n"
        "- Exposure to DevOps practices and CI/CD pipelines\n"
        "- Knowledge of data pipelines and basic ML concepts\n"
        "- Experience with vector databases or embeddings\n"
        "- Background in process optimisation or digital transformation\n"
        "\n"
        "What's on Offer\n"
        "\n"
        "- Fully remote UK-based role\n"
        "- Competitive salary (£55k-£80k DOE)\n"
        "- Opportunity to work on cutting-edge AI and automation projects\n"
        "- High autonomy and innovation-driven culture\n"
        "- Career progression into Lead Automation Engineer / AI Architect\n"
        "- Flexible working environment\n"
        "\n"
        "AI Automation Engineer, AI Engineer , Automation Engineer AI, LLM Engineer, "
        "AI Workflow Automation , Python Automation Engineer Remote, Generative AI "
        "Engineer\n"
        "... more"
    )
    file = "Linkedin_view.html"


class TestIndeedJobView(ScraperTestBase):

    title = "Embedded Software Engineer (UAV's)"
    company = "Archangel Aerospace Group"
    platform = "indeed"
    location = "1 Osney Mead, Oxford"
    attendance_type = None
    salary_min = 55_000
    salary_max = 65_000
    salary_currency = "GBP"
    description = (
        "Embedded Software Engineer\n"
        "\n"
        "We are looking for an experienced Embedded Software Engineer who combines "
        "practical software skills with a very strong academic background\n"
        "\n"
        "At Archangel Imaging, you will be working alongside a fun, experienced and "
        "forward-thinking team to deliver transformative AI solutions that help "
        "organisations like Network Rail, Nuclear Decommissioning Authority and "
        "Ministry of Defence better protect our service personnel, critical "
        "infrastructure and first responders over large, remote areas. But that's not "
        "all! We work extensively with industry drones and robotics partners to "
        "create turn-key solutions, so you will have exposure to the latest "
        "cutting-edge technologies.\n"
        "\n"
        "You will be joining a company that is enjoying great success. We have "
        "recently won the GENIUS NY program in New York (the largest accelerator "
        "program for unmanned systems in the world). In addition, we have won several "
        "exciting development projects with key defence customers.\n"
        "\n"
        "You must have these to apply:\n"
        "\n"
        "- BSc or MSc degree in Electrical Engineering, Computer Science, Computer "
        "Engineering, or related engineering field\n"
        "- 4+ Years of experience delivering functioning commercial embedded "
        "software\n"
        "- Excellent C/C++ skills\n"
        "- Familiarity with Python\n"
        "- Deep understanding of Linux internals, kernel programming, device trees\n"
        "- Experience writing and debugging drivers for novel hardware in Linux\n"
        "- Experience in debugging various interfaces (SPI, UART, CAN, USB etc.)\n"
        "- Practical skills in directly working with hardware\n"
        "- Ability to be on site in Oxford regularly during the week\n"
        "\n"
        "Nice to have:\n"
        "\n"
        "- Experience with Nvidia Jetson systems\n"
        "- Experience of kernel mode and bare-metal programming on ARM\n"
        "- Deep knowledge of camera systems to the sensor level\n"
        "- RTOS programming experience\n"
        "- Understanding of filesystems, networking, interprocess communication\n"
        "- Sound knowledge of control theory\n"
        "- Interest and experience in the Drone/UAS space\n"
        "- Knowledge of wireless communication systems\n"
        "- Interest in machine learning\n"
        "- Familiarity with GPS/GNSS positioning\n"
        "- Hardware and electronics rapid prototyping skills\n"
        "- Able to travel for events and field tests in the UK and abroad\n"
        "\n"
        "By joining us, you'll have:\n"
        "\n"
        "- The ability to make a measurable difference in a small company building "
        "cutting edge technology with big vision\n"
        "- Fast-paced environment with a positive, talented team\n"
        "- Forward-thinking, supportive culture with Monday paid lunch, quarterly "
        "company retreats and strategic alignment, flexible working hours, working "
        "from home and custom arrangements that matter to you\n"
        "- Exciting growth opportunities and training resources Including training to "
        "be a UAV pilot\n"
        "- Merit-based compensation\n"
        "- 5% employer pension contribution\n"
        "- 25 days holiday + UK bank holidays\n"
        "- Employee equity options scheme upon passing probation\n"
        "- A variety of perks: Gym discounts, Cycle2work, shopping, and supermarket "
        "discounts plus many more!\n"
        "- VR headset / DJI drone upon passing probation\n"
        "\n"
        "Interested?\n"
        "\n"
        "Apply now and someone from our HR team will get back to you ASAP. The usual "
        "process includes a screening call, a quick live coding test and then a "
        "meeting with more of the team to get to know each other. That's it!\n"
        "\n"
        "Sound interesting? Apply now and join us making the future\n"
        "\n"
        "Job Type: Full-time\n"
        "\n"
        "Pay: £55,000.00-£65,000.00 per year\n"
        "\n"
        "Schedule:\n"
        "\n"
        "- Monday to Friday\n"
        "\n"
        "Work Location: In person"
    )
    file = "Indeed_view.html"


class TestIndeedJobMain(ScraperTestBase):

    title = "Embedded Software Engineer (UAV's)"
    company = "Archangel Aerospace Group"
    platform = "indeed"
    location = "1 Osney Mead, Oxford"
    attendance_type = None
    salary_min = 55_000
    salary_max = 65_000
    salary_currency = "GBP"
    description = (
        "Embedded Software Engineer\n"
        "\n"
        "We are looking for an experienced Embedded Software Engineer who combines "
        "practical software skills with a very strong academic background\n"
        "\n"
        "At Archangel Imaging, you will be working alongside a fun, experienced and "
        "forward-thinking team to deliver transformative AI solutions that help "
        "organisations like Network Rail, Nuclear Decommissioning Authority and "
        "Ministry of Defence better protect our service personnel, critical "
        "infrastructure and first responders over large, remote areas. But that's not "
        "all! We work extensively with industry drones and robotics partners to "
        "create turn-key solutions, so you will have exposure to the latest "
        "cutting-edge technologies.\n"
        "\n"
        "You will be joining a company that is enjoying great success. We have "
        "recently won the GENIUS NY program in New York (the largest accelerator "
        "program for unmanned systems in the world). In addition, we have won several "
        "exciting development projects with key defence customers.\n"
        "\n"
        "You must have these to apply:\n"
        "\n"
        "- BSc or MSc degree in Electrical Engineering, Computer Science, Computer "
        "Engineering, or related engineering field\n"
        "- 4+ Years of experience delivering functioning commercial embedded "
        "software\n"
        "- Excellent C/C++ skills\n"
        "- Familiarity with Python\n"
        "- Deep understanding of Linux internals, kernel programming, device trees\n"
        "- Experience writing and debugging drivers for novel hardware in Linux\n"
        "- Experience in debugging various interfaces (SPI, UART, CAN, USB etc.)\n"
        "- Practical skills in directly working with hardware\n"
        "- Ability to be on site in Oxford regularly during the week\n"
        "\n"
        "Nice to have:\n"
        "\n"
        "- Experience with Nvidia Jetson systems\n"
        "- Experience of kernel mode and bare-metal programming on ARM\n"
        "- Deep knowledge of camera systems to the sensor level\n"
        "- RTOS programming experience\n"
        "- Understanding of filesystems, networking, interprocess communication\n"
        "- Sound knowledge of control theory\n"
        "- Interest and experience in the Drone/UAS space\n"
        "- Knowledge of wireless communication systems\n"
        "- Interest in machine learning\n"
        "- Familiarity with GPS/GNSS positioning\n"
        "- Hardware and electronics rapid prototyping skills\n"
        "- Able to travel for events and field tests in the UK and abroad\n"
        "\n"
        "By joining us, you'll have:\n"
        "\n"
        "- The ability to make a measurable difference in a small company building "
        "cutting edge technology with big vision\n"
        "- Fast-paced environment with a positive, talented team\n"
        "- Forward-thinking, supportive culture with Monday paid lunch, quarterly "
        "company retreats and strategic alignment, flexible working hours, working "
        "from home and custom arrangements that matter to you\n"
        "- Exciting growth opportunities and training resources Including training to "
        "be a UAV pilot\n"
        "- Merit-based compensation\n"
        "- 5% employer pension contribution\n"
        "- 25 days holiday + UK bank holidays\n"
        "- Employee equity options scheme upon passing probation\n"
        "- A variety of perks: Gym discounts, Cycle2work, shopping, and supermarket "
        "discounts plus many more!\n"
        "- VR headset / DJI drone upon passing probation\n"
        "\n"
        "Interested?\n"
        "\n"
        "Apply now and someone from our HR team will get back to you ASAP. The usual "
        "process includes a screening call, a quick live coding test and then a "
        "meeting with more of the team to get to know each other. That's it!\n"
        "\n"
        "Sound interesting? Apply now and join us making the future\n"
        "\n"
        "Job Type: Full-time\n"
        "\n"
        "Pay: £55,000.00-£65,000.00 per year\n"
        "\n"
        "Schedule:\n"
        "\n"
        "- Monday to Friday\n"
        "\n"
        "Work Location: In person"
    )
    file = "Indeed_main.html"


class TestNhsJob1(ScraperTestBase):

    title = "Nursing Associate - Community Nursing"
    company = "Mersey Care NHS Foundation Trust"
    platform = "nhs"
    location = "Tower Hill Health Centre, Croxteth, L6 2EH"
    attendance_type = None
    salary_min = 27_485
    salary_max = 30_162
    salary_currency = "GBP"
    description = (
        "Job summary\n"
        "\n"
        "Are you a Nursing Associate with a passion for delivering outstanding care "
        "that brings the 6 Cs (care, compassion, commitment, courage, communication "
        "and competence) to life? If so, we want to hear from you. The successful "
        "candidate must have demonstrable experience, a wide range of clinical skills "
        "and will be confident to work without direct supervision.\n"
        "\n"
        "The role will involve regular travel across multiple sites in the Mersey "
        "Care catchment area, therefore you must have the ability, means and "
        "willingness to travel in the course of your duties.\n"
        "\n"
        "Main duties of the job\n"
        "\n"
        "The role of the Nursing Associate is to work with the multi professional "
        "team and the Registered Nurse to assess, plan, organise and deliver clinical "
        "care in line with service and patient needs, as agreed with supervising "
        "clinicians.\n"
        "The Nursing Associate has a breadth of knowledge across the lifespan and "
        "across the fields of nursing, providing holistic and person centred care and "
        "support for people of all ages and in a variety of settings. The Nursing "
        "Associate works independently under the leadership of registered nurses, "
        "working within the sphere of nursing care and within all aspects of "
        "thenursing process (Health Education England 2018).\n"
        "Nursing Associates are accountable professionals who are equipped with the "
        "knowledge, understanding, skills, attitudes and behaviours relevant to "
        "employment as a Nursing Associate and will work to a nationally recognised "
        "Nursing and Midwifery Council (NMC) code of conduct. They must meet the NMC "
        "standards of proficiency and recognise and work within the limits of their "
        "competency.\n"
        "\n"
        "About us\n"
        "\n"
        "Mersey Care is one of the largest trusts providing physical health and "
        "mental health services in the North West, serving more than 1.4 million "
        "people across our region and are also commissioned for services that cover "
        "the North West, North Wales and the Midlands.\n"
        "We offer specialist inpatient and community services that support physical "
        "and mental health and specialist inpatient mental health, learning "
        "disability, addiction and brain injury services. Mersey Care is one of only "
        "three trusts in the UK that offer high secure mental health facilities.\n"
        "At the heart of all we do is our commitment to 'perfect care' - care that is "
        "safe, effective, positively experienced, timely, equitable and efficient. We "
        "support our staff to do the best job they can and work alongside service "
        "users, their families, and carers to design and develop future services "
        "together. We're currently delivering a programme of organisational and "
        "service transformation to significantly improve the quality of the services "
        "we provide and safely reduce cost as we do so.\n"
        "Flexible working requests will be considered for all roles.\n"
        "\n"
        "Job description\n"
        "\n"
        "Job responsibilities\n"
        "\n"
        "The Registered Nursing Associate (RNA) will work as part of the "
        "multidisciplinary team within the Mersey Care District Nursing service, "
        "delivering high-quality, person-centred care under the direction of "
        "registered nurses. The RNA will contribute to the assessment, planning, "
        "implementation, and evaluation of care, supporting patients with a range of "
        "health needs in their own homes and community settings.\n"
        "Main Responsibilities\n"
        "- Deliver safe and effective care to patients in line with individual care "
        "plans and clinical guidelines.\n"
        "- Support registered nurses in the assessment and monitoring of patients, "
        "escalating concerns appropriately.\n"
        "- Administer medications and treatments within scope of practice and in "
        "accordance with NMC standards.\n"
        "- Promote health and wellbeing through education, advice, and support to "
        "patients and carers.\n"
        "- Maintain accurate and timely clinical records using electronic systems.\n"
        "- Participate in clinical audits, quality improvement initiatives, and "
        "service development.\n"
        "- Work collaboratively with other health and social care professionals to "
        "ensure coordinated care.\n"
        "- Uphold professional standards and contribute to a culture of continuous "
        "learning and development.\n"
        "- Supervise and support junior staff and students as appropriate.\n"
        "- Adhere to Mersey Cares values and policies, including safeguarding, "
        "infection control, and equality and diversity.\n"
        "\n"
        "Person Specification\n"
        "\n"
        "Skills\n"
        "\n"
        "Essential\n"
        "\n"
        "- Excellent interpersonal and communication skills\n"
        "- IT skills appropriate to the role\n"
        "- Ability to work well in a team\n"
        "- Ability to work on own initiative\n"
        "- Ability to organise and prioritise own workload\n"
        "- Able to recognise own limitations in the context of the Nursing Associate "
        "role\n"
        "- Ability to participate in reflective practice and clinical supervision "
        "activities.\n"
        "\n"
        "Knowledge/Experience\n"
        "\n"
        "Essential\n"
        "\n"
        "- Previous experience of working within a healthcare setting\n"
        "- Experience of working in teams under appropriate supervision as part of a "
        "multi-disciplinary team\n"
        "- Insight into how to evaluate own strengths and development needs, seeking "
        "advice where appropriate\n"
        "- Experience of providing and receiving complex, sensitive information\n"
        "- Breadth of person centred nursing knowledge\n"
        "- Understanding of the scope of the role of the Nursing Associate in context "
        "of the nursing and interdisciplinary team and the organisation, and how the "
        "role may contribute to service development\n"
        "- Understands and acts in line with NMC professional standards for practice "
        "contained within The Code\n"
        "- Knowledge of when to seek advice and escalate to the appropriate "
        "professional for expert help and advice\n"
        "- Understand requirements for NMC professional Revalidation\n"
        "- Understanding of the importance of following procedures and treatment "
        "plans\n"
        "\n"
        "Qualifications\n"
        "\n"
        "Essential\n"
        "\n"
        "- Foundation Degree in Nursing Associate practice\n"
        "- Current NMC Registration\n"
        "\n"
        "Values\n"
        "\n"
        "Essential\n"
        "\n"
        "- Continuous Improvement\n"
        "- Accountability\n"
        "- Respectfulness\n"
        "- Enthusiasm\n"
        "- Support\n"
        "- High professional standards\n"
        "- Responsive to service users\n"
        "- Engaging leadership style\n"
        "- Strong customer service belief\n"
        "- Transparency and honesty\n"
        "- Discreet\n"
        "- Change oriented\n"
        "\n"
        "Disclosure and Barring Service Check\n"
        "\n"
        "This post is subject to the Rehabilitation of Offenders Act (Exceptions "
        "Order) 1975 and as such it will be necessary for a submission for Disclosure "
        "to be made to the Disclosure and Barring Service (formerly known as CRB) to "
        "check for any previous criminal convictions.\n"
        "\n"
        "UK Registration\n"
        "\n"
        "Applicants must have current UK professional registration. For further "
        "information please see\n"
        "NHS Careers website (opens in a new window).\n"
        "\n"
        "Employer details\n"
        "\n"
        "Employer name\n"
        "\n"
        "Mersey Care NHS Foundation Trust\n"
        "\n"
        "Address\n"
        "\n"
        "Tower Hill Health Centre\n"
        "\n"
        "Croxteth\n"
        "\n"
        "L6 2EH\n"
        "\n"
        "Employer's website\n"
        "\n"
        "https://www.merseycare.nhs.uk/ (Opens in a new tab)"
    )
    file = "nhs_1.html"


class TestVeganjobsJob1(ScraperTestBase):

    title = "Graphic Designer"
    company = "Educated Choices Program"
    platform = "veganjobs"
    location = None
    attendance_type = "remote"
    salary_min = None
    salary_max = None
    salary_currency = None
    description = (
        "Job Overview\n"
        "The ECP Graphic Designer may (but is not limited to), assist with "
        "Communications department tasks, such as:\n"
        "\n"
        "- Visual Asset Creation: Design high-quality, clear, and engaging digital "
        "and print materials, including social media graphics, email headers, videos, "
        "landing pages, flyers, billboards, public-facing documents, and other "
        "graphic designs.\n"
        "- Edit short-form educational reels\n"
        "- Create simple motion graphics and animated text overlays\n"
        "- Typical weekly projects may include:\n"
        "- 3-5 social graphics\n"
        "- 1-2 carousel posts\n"
        "- Newsletter, blog, and PR assets\n"
        "- Brand Stewardship: Adhere to brand guidelines (color palettes, typography, "
        "and logo usage) to ensure consistency across all channels.\n"
        "- Concept Development: Collaborate with the marketing or creative team to "
        "brainstorm and execute original visual concepts for specific campaigns.\n"
        "\n"
        "\u200bPreferred Qualifications:\u200b\n"
        "\n"
        "- Proficient in Google Workspace\n"
        "- Experience working in  Monday.com  or similar task management systems\n"
        "- Experience in Canva and Adobe Creative Cloud applications (Illustrator, "
        "Photoshop)\n"
        "- Strong and diverse design portfolio\n"
        "- Experience in the academic or nonprofit sectors\n"
        "- Ability to communicate clearly and work effectively with minimal "
        "supervision\n"
        "- Ability to freehand draw illustrations, create digital designs, and "
        "produce short videos\n"
        "- Strong organizational skills and attention to detail\n"
        "- Flexible and open to feedback\n"
        "- Fully bilingual in English and Spanish is a bonus\n"
        "- Experience designing for Instagram, Facebook, LinkedIn, and YouTube\n"
        "- Understanding of carousel design strategy and engagement-driven layouts\n"
        "\n"
        "\u200b\n"
        "Tagged as: design, media, social media, video production, content creation, "
        "graphic design, communications, brand strategy"
    )
    file = "veganjobs_1.html"


class TestVeganjobsJob2(ScraperTestBase):

    title = "Animal Caregiver"
    company = "Piedmont Farm Animal Refuge"
    platform = "veganjobs"
    location = "Pittsboro, North Carolina"
    attendance_type = None
    salary_min = None
    salary_max = None
    salary_currency = None
    description = (
        "Job Overview\n"
        "We are seeking an Animal Caregiver to join our dedicated team of passionate "
        "animal lovers! Our ideal candidate would be committed to becoming a longterm "
        "member of our team, and would be excited to work alongside other staff "
        "members to help our organization continue to grow.\n"
        "Piedmont Farm Animal Refuge is a sanctuary for farmed animals who are "
        "rescued from abuse, neglect and abandonment. Located in Pittsboro North "
        "Carolina, the Refuge is home to over 100 goats, sheep, chickens, turkeys, "
        "ducks, geese, cows, and one guinea fowl, who are provided with high quality "
        "healthcare, daily enrichment, and animal-centered homes. The Refuge offers "
        "tours, vegan cooking classes, and other educational programs designed to "
        "inspire a compassionate vegan lifestyle.\n"
        "The Refuge is located about 20 minutes from Carrboro, Chapel Hill and "
        "Saxapahaw and about 45 minutes from Raleigh, Durham and Greensboro. Job "
        "responsibilities, qualifications and specifics are listed below.\n"
        "Responsibilities\n"
        "\n"
        "- Daily animal feeding, watering, enrichment and socialization\n"
        "- Daily animal medications, treatments and other health care\n"
        "- Daily cleaning of animal houses and outdoor environments\n"
        "- Updating and maintaining animal records\n"
        "- Training and supervising volunteers and interns\n"
        "- Working closely with the Animal Care Director, Caregiving Team and other "
        "staff members\n"
        "- Conducting weekly purchases and storage of hay, straw, feed, and other "
        "animal supplies\n"
        "- Transporting animals to vet appointments and communicating with "
        "veterinarians\n"
        "- Maintaining neat and organized work and storage spaces\n"
        "- Capturing photographs and videos of the animal residents\n"
        "- Assisting with animal rescues and transports as needed\n"
        "- Other duties, as assigned\n"
        "\n"
        "Qualifications\n"
        "\n"
        "- Previous animal experience is required\n"
        "- Commitment to the mission of Piedmont Farm Animal Refuge\n"
        "- Knowledge of and passion for animal rights issues and veganism is strongly "
        "preferred\n"
        "- Excellent animal behavior observation skills\n"
        "- Able and willing to work in all weather conditions\n"
        "- Able and willing to perform strenuous physical labor and lift up to 50 "
        "pounds\n"
        "- Able to follow detailed instructions and meet time sensitive demands\n"
        "- Able to learn and process new information quickly\n"
        "- Strong communication and listening skills\n"
        "- Excellent interpersonal skills, including ability to interact "
        "constructively with volunteers, staff, and the general public\n"
        "- Experience managing volunteers is strongly preferred\n"
        "- Resourcefulness and ability to work independently\n"
        "- Strong time management skills with ability to multi-task efficiently\n"
        "- Able to handle confidential and sensitive information\n"
        "- Basic knowledge of Microsoft Word, Excel, Google Drive, and social media "
        "platforms\n"
        "- Flexible schedule to meet onsite program requirements; weekend, evening "
        "and holiday hours are required as needed\n"
        "- Valid driver's license and clean criminal background check\n"
        "\n"
        "Job Specifics\n"
        "\n"
        "- Full time permanent position at 40 hours per week\n"
        "- Starting wage is $17 - $19 per hour, based on experience\n"
        "- Regular schedule includes weekends and holidays, as needed\n"
        "- BENEFITS: 120 hrs of Paid Time Off per year (equivalent of 3 weeks), ICHRA "
        "health insurance, opportunities for professional development & networking, "
        "mental health support, access to Premium Calm App, and discounts through the "
        "Working Advantage Program\n"
        "\n"
        "To apply please submit a cover letter, resume and two work-related "
        "references to Lenore Braford at: lenore@piedmontrefuge.org\n"
        "Piedmont Farm Animal Refuge is an equal opportunity employer. Piedmont Farm "
        "Animal prohibits discrimination and harassment of any type and affords equal "
        "employment opportunities to employees and applicants without regard to race, "
        "color, religion, sex, sexual orientation, gender identity or expression, "
        "pregnancy, age, national origin, disability status, genetic information, "
        "protected veteran status, or any other characteristic protected by law. "
        "Piedmont Farm Animal conforms to the spirit as well as to the letter of all "
        "applicable laws and regulations.\n"
        " \n"
        "\n"
        " \n"
        "Tagged as: animal rescue, animal sanctuary, animal care, volunteer "
        "management, veterinary, nonprofit"
    )
    file = "veganjobs_2.html"
